# Generated by Django 3.1.3 on 2021-01-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniad', '0002_auto_20210104_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='channel',
            field=models.TextField(null=True),
        ),
    ]
